### ISSUE TITLE
Support for generic handlers

### ISSUE THREAD

**Issue by greydot** [AJChapman/servant-polysemy#2]
Is there a way to use this library with Servant.API.Generic-style handlers?

**Comment by AJChapman** [comment]
Yes, I've just tried this out and added it as an example. See https://github.com/AJChapman/servant-polysemy/blob/master/example/ServerGeneric.hs

**Comment by greydot** [comment]
Oh wow! Thank you!

I tried this, but couldn't get past the ambiguous type variable error.
